# Setup
title:               RB
tagline:             ''
description:         'A collection of articles written by Roel Bondoc'
url:                 https://blog.roelbondoc.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Roel Bondoc
  url:               https://twitter.com/roelbondoc
  email:             me@roelbondoc.com

# Gems
plugins:
  - jekyll-paginate
